<div class="row content">
    <div class="container">
        <div class="box">
            <div class="col-sm-3">
                <img src="img/box.png" alt="" class="img-responsive"/>
                <h3><a href="#">o nas</a></h3>
                <h4>Dowiedz się więcej o naszej placówce</h4>
            </div>
            <div class="col-sm-3">
                <img src="img/box.png" alt="" class="img-responsive"/>
                <h3><a href="#">o nas</a></h3>
                <h4>Dowiedz się więcej o naszej placówce</h4>
            </div>
            <div class="col-sm-3">
                <img src="img/box.png" alt="" class="img-responsive"/>
                <h3><a href="#">o nas</a></h3>
                <h4>Dowiedz się więcej o naszej placówce</h4>
            </div>
            <div class="col-sm-3">
                <img src="img/box.png" alt="" class="img-responsive"/>
                <h3><a href="#">o nas</a></h3>
                <h4>Dowiedz się więcej o naszej placówce</h4>
            </div>
        </div>
    </div>
    <div class="col-sm-12 invitation">
        <div class="container">
            <a href="#">Pro Comunications zaprasza <img src="img/big-arrow.png" alt="" class="big-arrow"/></a>
        </div>
    </div>

    <div class="col-sm-12 head">
        <div class="container">
            <h1>dlaczego my?</h1>
        </div>
    </div>

    <div class="col-sm-12">
        <div class="container text">
            <div class="row">
                <div class="col-sm-8">
                    Jesteśmy pierwszym na Śląsku gabinetem zajmującym się terapią i wspieraniem rozwoju dzieci i dorosłych u których stwierdzono:
                    <ul>
                        <li>kłopoty z koncetracją i pamięcią</li>
                        <li>ADHD/ADD (zespół nadpobudliwości ruchowej z deficytem uwagi)</li>
                        <li>zaburzenia mowy i wady wymowy</li>
                        <li>trudności w kontaktach społecznych</li>
                        <li>dyslekcję</li>
                        <li>zespół Aspergera, Autyzm</li>
                        <li>porażenie mózgowe</li>
                        <li>Zespół Downa</li>
                    </ul>

                    Prowadzimy także zajęcia i terapie:
                    <ul>
                        <li>dla osób z dolegliwoścmia takimi jak: nerwice, depresje, bezsenność</li>
                        <li>dla kobiet w ciąży jako wyciszenie i przygotowanie do porodu</li>
                        <li>dla dzieci i dorosłych uczących się języków obcych</li>
                        <li>dla osób zawodowo pracujących głosem (lekarzy, aktorzy, śpiewacy, nauczyciele)</li>
                        <li>dla studentów, menageróew, oraz wszystkich chętnych jako pomoc w rozwoju własnego potencjału intelektualnego, a także w celu rozwiązywania problemów z głosem i słuchem oraz walce ze stresem.</li>
                    </ul>
                </div>
                <div class="col-sm-4"><img class="img-responsive" src="img/dlaczego.png" alt=""/></div>
            </div>
            <div class="row more-div">
                <div class="col-sm-12">
                    <a class="more" href="#">dowiedz się więcej</a>
                </div>
            </div>
        </div>
    </div>
</div>