<div class="row content">
    <div class="container">
        <div class="box">
            <div class="col-sm-3">
                <img src="img/box.png" alt="" class="img-responsive"/>
                <h3><a href="#">o nas</a></h3>
                <h4>Dowiedz się więcej o naszej placówce</h4>
            </div>
            <div class="col-sm-3">
                <img src="img/box.png" alt="" class="img-responsive"/>
                <h3><a href="#">o nas</a></h3>
                <h4>Dowiedz się więcej o naszej placówce</h4>
            </div>
            <div class="col-sm-3">
                <img src="img/box.png" alt="" class="img-responsive"/>
                <h3><a href="#">o nas</a></h3>
                <h4>Dowiedz się więcej o naszej placówce</h4>
            </div>
            <div class="col-sm-3">
                <img src="img/box.png" alt="" class="img-responsive"/>
                <h3><a href="#">o nas</a></h3>
                <h4>Dowiedz się więcej o naszej placówce</h4>
            </div>
        </div>
    </div>
    <div class="col-sm-12 invitation">
        <div class="container">
            <a href="#">Pro Comunications zaprasza <img src="img/big-arrow.png" alt="" class="big-arrow"/></a>
        </div>
    </div>

    <div class="col-sm-12 head">
        <div class="container">
            <h1>dlaczego my?</h1>
        </div>
    </div>

    <div class="col-sm-12">
        <div class="container text">
            <div class="row">
                <div class="col-sm-8">
                    Jesteśmy pierwszym na Śląsku gabinetem zajmującym się terapią i wspieraniem rozwoju dzieci i dorosłych u których stwierdzono:
                    <ul>
                        <li>kłopoty z koncetracją i pamięcią</li>
                        <li>ADHD/ADD (zespół nadpobudliwości ruchowej z deficytem uwagi)</li>
                        <li>zaburzenia mowy i wady wymowy</li>
                        <li>trudności w kontaktach społecznych</li>
                        <li>dyslekcję</li>
                        <li>zespół Aspergera, Autyzm</li>
                        <li>porażenie mózgowe</li>
                        <li>Zespół Downa</li>
                    </ul>

                    Prowadzimy także zajęcia i terapie:
                    <ul>
                        <li>dla osób z dolegliwoścmia takimi jak: nerwice, depresje, bezsenność</li>
                        <li>dla kobiet w ciąży jako wyciszenie i przygotowanie do porodu</li>
                        <li>dla dzieci i dorosłych uczących się języków obcych</li>
                        <li>dla osób zawodowo pracujących głosem (lekarzy, aktorzy, śpiewacy, nauczyciele)</li>
                        <li>dla studentów, menageróew, oraz wszystkich chętnych jako pomoc w rozwoju własnego potencjału intelektualnego, a także w celu rozwiązywania problemów z głosem i słuchem oraz walce ze stresem.</li>
                    </ul>
                </div>
                <div class="col-sm-4"><img class="img-responsive" src="img/dlaczego.png" alt=""/></div>
            </div>
            <div class="row more-div">
                <div class="col-sm-12">
                    <a class="more" href="#">dowiedz się więcej</a>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="col-sm-12 contact">
    <div class="container">
        <div class="row">
            <div class="col-sm-3">
                <h4>skontaktuj się z nami</h4>

                <span>Pro Comunications Grabinet Terapii i Rozwoju</span>
                ul. Kossak-Szczuckiej 32 <br/>
                40-578 Katowice <br/> <br/>

                tel. 601 290 441 <br/>
                <a href="mailto:a.nowinska@terapiairozwoj.pl">a.nowinska@terapiairozwoj.pl</a> <br/> <br/>

                <span>Rachunek Bankowy:</span>
                ING BANK ŚŁĄSKI <br/>
                55 1050 1214 1000 0090 7112 6099
            </div>
            <div class="col-sm-6">
                <h4>gdzie nas znajdziesz?</h4>
                <iframe src="https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d2552.1336941167315!2d18.9844094!3d50.2334072!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x4716ce8d42961a8f%3A0x74d46de625adb3f6!2sKossak-Szczuckiej+32%2C+40-578+Katowice!5e0!3m2!1spl!2spl!4v1426705019410" width="100%" height="300" frameborder="0" style="border:0"></iframe>
            </div>
            <div class="col-sm-3">
                <h4>nasza galeria</h4>

                <div class="gallery">
                    <div>
                        <img class="img-responsive" src="img/przedszkole.png" alt=""/>
                        <img class="img-responsive" src="img/przedszkole.png" alt=""/>
                        <img class="img-responsive" src="img/przedszkole.png" alt=""/>
                        <img class="img-responsive" src="img/przedszkole.png" alt=""/>
                    </div>

                    <div>
                        <img class="img-responsive" src="img/przedszkole.png" alt=""/>
                        <img class="img-responsive" src="img/przedszkole.png" alt=""/>
                        <img class="img-responsive" src="img/przedszkole.png" alt=""/>
                        <img class="img-responsive" src="img/przedszkole.png" alt=""/>
                    </div>

                    <div>
                        <img class="img-responsive" src="img/przedszkole.png" alt=""/>
                        <img class="img-responsive" src="img/przedszkole.png" alt=""/>
                        <img class="img-responsive" src="img/przedszkole.png" alt=""/>
                        <img class="img-responsive" src="img/przedszkole.png" alt=""/>
                    </div>
                </div>

                <div class="row more-div">
                    <div class="col-sm-12">
                        <a class="more" href="#">zobacz więcej</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>