<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle($this->translate('Przedszkole')) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        // MAIN CSS (REQUIRED ALL PAGE)
                        ->appendStylesheet($this->basePath() . '/css/bootstrap.min.css')
                        ->appendStylesheet($this->basePath() . '/css/b-owl.carousel.css')
                        ->appendStylesheet($this->basePath() . '/css/b-owl.theme.css')
                        ->appendStylesheet($this->basePath() . '/css/b-owl.transitions.css')
                        ->appendStylesheet($this->basePath() . '/css/b-jquery.fancybox.css')
                        ->appendStylesheet($this->basePath() . '/css/b-style.css')
                        ->appendStylesheet($this->basePath() . '/css/b-media_queries.css')
        ?>

        <link rel="stylesheet" type="text/css" href="http://fonts.googleapis.com/css?family=Ek+Mukta">
        <link href='http://fonts.googleapis.com/css?family=Open+Sans:400,800,600,300&subset=latin,cyrillic-ext,greek-ext,greek,vietnamese,latin-ext,cyrillic' rel='stylesheet' type='text/css'>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->appendFile($this->basePath() . '/js/jquery.min.js', 'text/javascript')
            ->appendFile($this->basePath() . '/js/jquery.fancybox.js', 'text/javascript')
            ->appendFile($this->basePath() . '/js/owl.carousel.min.js', 'text/javascript')
            ->appendFile($this->basePath() . '/js/blekitna-script.js',   'text/javascript');
        ?>

    </head>
    <body>

        <a class="change-site" href="/pro-comunications"><img src="/img/button_pc.png" alt="button"/></a>
        <?php echo $this->partial('partial-blekitna/layout/header'); ?>
        <?php echo $content; ?>
        <?php echo $this->partial('partial-blekitna/layout/footer'); ?>

        <?php echo $this->inlineScript() ?>

    </body>
</html>
