<?php if ($this->flashMessenger()->hasMessages() || $this->flashMessenger()->hasErrorMessages()) : ?>

<?php
    $flash = $this->flashMessenger();
    $flash->setMessageOpenFormat(
                '<div%s>
                    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">
                        &times;
                    </button>
                    <strong>Komuniakt:</strong><br />
                ')
          ->setMessageCloseString('</div>');

    echo $flash->render('error',   array('alert', 'alert-dismissable', 'alert-bold-border fade in', 'alert-danger'));
    echo $flash->render('info',    array('alert', 'alert-dismissable', 'alert-bold-border fade in', 'alert-info'));
    echo $flash->render('default', array('alert', 'alert-dismissable', 'alert-bold-border fade in', 'alert-success'));
    echo $flash->render('success', array('alert', 'alert-dismissable', 'alert-bold-border fade in', 'alert-success'));
?>

<?php endif; ?>
