<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle($this->translate('Pro communications')) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        // MAIN CSS (REQUIRED ALL PAGE)
                        ->appendStylesheet($this->basePath() . '/css/bootstrap.min.css')
                        ->appendStylesheet($this->basePath() . '/css/owl.carousel.css')
                        ->appendStylesheet($this->basePath() . '/css/owl.theme.css')
                        ->appendStylesheet($this->basePath() . '/css/owl.transitions.css')
                        ->appendStylesheet($this->basePath() . '/css/jquery.fancybox.css')
                        ->appendStylesheet($this->basePath() . '/css/main-style.css')
        ?>

        <link rel="stylesheet" type="text/css" href="http://fonts.googleapis.com/css?family=Ek+Mukta">
        <link href='http://fonts.googleapis.com/css?family=Open+Sans:400,800,600,300&subset=latin,cyrillic-ext,greek-ext,greek,vietnamese,latin-ext,cyrillic' rel='stylesheet' type='text/css'>
        <link rel="stylesheet" href="/css/media_queries.css">
        <script src="http://code.jquery.com/jquery-1.11.2.min.js"></script>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->appendFile($this->basePath() . '/js/owl.carousel.min.js', 'text/javascript')
            ->appendFile($this->basePath() . '/js/jquery.fancybox.js', 'text/javascript')
            ->appendFile($this->basePath() . '/js/script.js',   'text/javascript');
        ?>

    </head>
    <body>
        <a class="fb" href="https://www.facebook.com/pages/terapiairozwojpl/176654225706523?fref=ts"><img src="/img/fb.png" alt="facebok"/></a>

        <?php echo $this->partial('partial/layout/header'); ?>
        <?php echo $content; ?>
        <?php echo $this->partial('partial/layout/footer'); ?>

        <?php echo $this->inlineScript() ?>

    </body>
</html>
