<div class="col-sm-12 contact">
    <div class="container">
        <div class="row">
            <div class="col-sm-3">
                <h4>skontaktuj się z nami</h4>

                <span>NIEPUBLICZNY SPECJALNY PUNK PRZEDSZKOLNY "BŁĘKITNA KRAINA"</span>
                ul. Kossak-Szczuckiej 32 <br/>
                40-578 Katowice <br/> <br/>

                <span>Rachunek Bankowy:</span>
                ING BANK ŚŁĄSKI <br/>
                55 1050 1214 1000 0090 7112 6099

                <div class="contact-head">telefon</div>
                601 290 441
            </div>
            <div class="col-sm-3">
                <div class="clear"></div>
                <div class="clear"></div>

                <span style="margin-top: 7px;">Organ prowadzący</span>
                Agnieszka Nowińska <br/>
                ul. Fliegera 16/46 <br/>
                40-060 Katowice <br/>
                NIP: 6341096369 <br/>
                REGON: 24306311
                <br/><br/><br/><br/><br/>
                <div class="contact-head" style="margin-top: 15px;">e-mail</div>
                <a href="mailto:a.nowinska@terapiairozwoj.pl">a.nowinska@terapiairozwoj.pl</a> <br/> <br/>

            </div>
            <div class="col-sm-3">
                <h4>gdzie nas znajdziesz?</h4>
                <iframe src="https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d2552.1336941167315!2d18.9844094!3d50.2334072!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x4716ce8d42961a8f%3A0x74d46de625adb3f6!2sKossak-Szczuckiej+32%2C+40-578+Katowice!5e0!3m2!1spl!2spl!4v1426705019410" width="100%" height="300" frameborder="0" style="border:0"></iframe>
            </div>
            <div class="col-sm-3">
                <h4>nasza galeria</h4>

                <div class="gallery">

                    <?php $files = array_chunk($files, 4) ?>
                    <?php foreach($files as $file): ?>

                        <div>

                            <?php foreach($file as $f): ?>

<!--                                <img class="img-circle" src="/files/file/--><?php //echo $f ?><!--" alt=""/>-->
                                <img class="img-circle" src="<?php echo $this->basePath() ?><?php echo $this->url('thumb', array('entity' => 'file', 'size' => '53x53', 'filename' => $f)); ?>" alt=""/>

                            <?php endforeach ?>

                        </div>

                    <?php endforeach ?>

                </div>

                <div class="row more-div">
                    <div class="col-sm-12">
                        <a class="more" href="<?php echo $this->url('blekitna-viewGallery') ?>">zobacz więcej</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="col-sm-12 footer-div">
    <div class="container footer">
        <div class="row">
            <div class="col-sm-9">
                <?php echo $this->menuHelper()->renderFooterMenu($menu, null, null, null, null); ?>
            </div>
            <div class="col-sm-3">
                <h4>Pro Comunications © 2014</h4>
                <div>Wszelkie prawa zastrzeżone</div>
                <img src="/img/fabryka.png" alt=""/>
                <div class="project">Projekt i wykonanie:</div>
            </div>
        </div>
    </div>
</div>