<div class="row content">
    <div class="container">
        <div class="box">
            <div class="col-sm-3">
                <img src="img/box.png" alt="" class="img-responsive"/>
                <h3><a href="<?php echo $this->url('blekitna-viewPage', array('slug' => 'o-nas')) ?>">o nas</a></h3>
                <h4>Dowiedz się więcej o naszej placówce</h4>
            </div>
            <div class="col-sm-3">
                <img src="img/oferta-1.png" alt="" class="img-responsive"/>
                <h3><a href="<?php echo $this->url('blekitna-viewPage', array('slug' => 'arteterapia')) ?>">oferta</a></h3>
                <h4>Zapoznaj się z naszą ofertą</h4>
            </div>
            <div class="col-sm-3">
                <img src="img/dokumenty-1.png" alt="" class="img-responsive"/>
                <h3><a href="<?php echo $this->url('blekitna-dokumenty') ?>">dokumenty</a></h3>
                <h4>Przejrzyj potrzebne pisma by zapisać swoje dziecko</h4>
            </div>
            <div class="col-sm-3">
                <img src="img/kontakt-1.png" alt="" class="img-responsive"/>
                <h3><a href="<?php echo $this->url('blekitna-viewContact') ?>">kontakt</a></h3>
                <h4>Masz pytanie? Skontaktuj się</h4>
            </div>
        </div>
    </div>
    <div class="col-sm-12 invitation">
        <div class="container">
            <a href="<?php echo $this->url('blekitna-viewContact') ?>">Błękitna Kraina zaprasza <img src="img/big-arrow.png" alt="" class="big-arrow"/></a>
        </div>
    </div>

    <div class="col-sm-12 head">
        <div class="container">
            <h1>dlaczego my?</h1>
        </div>
    </div>

    <div class="col-sm-12">
        <div class="container text">
            <?php $i = 0 ?>
            <?php /* @var $post \CmsIr\Post\Model\Post */ ?>
            <?php foreach($posts as $post): ?>
                <?php /* @var $file \CmsIr\Post\Model\PostFile */ ?>
                <?php $file = $post->getFiles() ?>

                <div class="clear"></div>
                <div class="row">
                    <?php if($i % 2 != 0): ?>
                        <div class="col-sm-3">
                            <?php if(!empty($file)): ?>
                                <img class="img-responsive" src="/files/post/<?php echo $file->getFilename() ?>" alt=""/>
                            <?php endif ?>
                        </div>
                    <?php endif ?>

                    <div class="col-sm-9">


                        <!--                            <h6>Arte - kinezjologia</h6>-->
                        <br/>
                        <?php echo $post->getText() ?>
                    </div>
                    <?php if($i % 2 == 0): ?>
                        <div class="col-sm-3">
                            <?php if(!empty($file)): ?>
                                <img class="img-responsive" src="/files/post/<?php echo $file->getFilename() ?>" alt=""/>
                            <?php endif ?>
                        </div>
                    <?php endif ?>
                </div>

                <?php $i++ ?>
            <?php endforeach ?>
            <div class="row more-div">
                <div class="col-sm-12">
                    <a class="more" href="<?php echo $this->url('blekitna-viewPage', array('slug' => 'o-nas')) ?>">dowiedz się więcej</a>
                </div>
            </div>
        </div>
    </div>
</div>