<div class="row content">

    <div class="col-sm-12 head">
        <div class="container">
            <h1>nasza kadra</h1>
        </div>
    </div>

    <div class="col-sm-12">
        <div class="container text">
            <div class="clear"></div>

            <?php $bosses = array_chunk($bosses, 2) ?>
            <?php foreach($bosses as $boss): ?>

                <div class="row">

                    <?php /* @var $b \CmsIr\Users\Model\Users */ ?>
                    <?php foreach($boss as $b): ?>

                        <div class="col-sm-6">
                            <img class="img-responsive employer" src="img/czlowiek.png" alt=""/>
                            <h6>mgr Agnieszka Nowińska</h6>
                            <div class="position"><b>właściciel</b>, oligofrenopedagog, certyfikowany terapeuta i konsultant metody Tomatisa, terapeuta metody Warnkego</div>
                        </div>

                    <?php endforeach ?>

                </div>

            <?php endforeach ?>
            <div class="row">
                <div class="col-sm-6">
                    <img class="img-responsive employer" src="img/czlowiek.png" alt=""/>
                    <h6>mgr Agnieszka Nowińska</h6>
                    <div class="position"><b>właściciel</b>, oligofrenopedagog, certyfikowany terapeuta i konsultant metody Tomatisa, terapeuta metody Warnkego</div>
                </div>
                <div class="col-sm-6">
                    <img class="img-responsive employer" src="img/czlowiek.png" alt=""/>
                    <h6>mgr Agnieszka Nowińska</h6>
                    <div class="position"><b>właściciel</b>, oligofrenopedagog, certyfikowany terapeuta i konsultant metody Tomatisa, terapeuta metody Warnkego</div>
                </div>
            </div>

            <div class="clear"></div>
            <div class="row">
                <div class="col-sm-3">
                    <img class="img-responsive employer" src="img/czlowiek.png" alt=""/>
                    <h6>mgr Agnieszka Nowińska</h6>
                    <div class="position">Tomatisa, terapeuta metody Warnkego</div>
                </div>
                <div class="col-sm-3">
                    <img class="img-responsive employer" src="img/czlowiek.png" alt=""/>
                    <h6>mgr Agnieszka Nowińska</h6>
                    <div class="position">Tomatisa, terapeuta metody Warnkego</div>
                </div>
                <div class="col-sm-3">
                    <img class="img-responsive employer" src="img/czlowiek.png" alt=""/>
                    <h6>mgr Agnieszka Nowińska</h6>
                    <div class="position">Tomatisa, terapeuta metody Warnkego</div>
                </div>
                <div class="col-sm-3">
                    <img class="img-responsive employer" src="img/czlowiek.png" alt=""/>
                    <h6>mgr Agnieszka Nowińska</h6>
                    <div class="position">Tomatisa, terapeuta metody Warnkego</div>
                </div>

                <div class="clear"></div>

                <div class="col-sm-3">
                    <img class="img-responsive employer" src="img/czlowiek.png" alt=""/>
                    <h6>mgr Agnieszka Nowińska</h6>
                    <div class="position">Tomatisa, terapeuta metody Warnkego</div>
                </div>
                <div class="col-sm-3">
                    <img class="img-responsive employer" src="img/czlowiek.png" alt=""/>
                    <h6>mgr Agnieszka Nowińska</h6>
                    <div class="position">Tomatisa, terapeuta metody Warnkego</div>
                </div>
                <div class="col-sm-3">
                    <img class="img-responsive employer" src="img/czlowiek.png" alt=""/>
                    <h6>mgr Agnieszka Nowińska</h6>
                    <div class="position">Tomatisa, terapeuta metody Warnkego</div>
                </div>
                <div class="col-sm-3">
                    <img class="img-responsive employer" src="img/czlowiek.png" alt=""/>
                    <h6>mgr Agnieszka Nowińska</h6>
                    <div class="position">Tomatisa, terapeuta metody Warnkego</div>
                </div>
            </div>

        </div>
    </div>


    <div class="col-sm-12 head">
        <div class="container">
            <div class="clear"></div>
            <h1>wychowawcy</h1>
        </div>
    </div>

    <div class="col-sm-12">
        <div class="container text">

            <div class="clear"></div>
            <div class="row">
                <div class="col-sm-6">
                    <p class="position">Wioska Smerfów</p>
                    <div class="row">
                        <div class="col-sm-6">
                            <img class="img-responsive employer" src="img/czlowiek.png" alt=""/>
                            <h6>mgr Agnieszka Nowińska</h6>
                            <div class="position">Tomatisa, terapeuta metody Warnkego</div>
                        </div>
                        <div class="col-sm-6">
                            <img class="img-responsive employer" src="img/czlowiek.png" alt=""/>
                            <h6>mgr Agnieszka Nowińska</h6>
                            <div class="position">Tomatisa, terapeuta metody Warnkego</div>
                        </div>
                    </div>
                </div>

                <div class="col-sm-6">
                    <p class="position">Wioska Smerfów</p>
                    <div class="row">
                        <div class="col-sm-6">
                            <img class="img-responsive employer" src="img/czlowiek.png" alt=""/>
                            <h6>mgr Agnieszka Nowińska</h6>
                            <div class="position">Tomatisa, terapeuta metody Warnkego</div>
                        </div>
                        <div class="col-sm-6">
                            <img class="img-responsive employer" src="img/czlowiek.png" alt=""/>
                            <h6>mgr Agnieszka Nowińska</h6>
                            <div class="position">Tomatisa, terapeuta metody Warnkego</div>
                        </div>
                    </div>
                </div>

                <div class="col-sm-6">
                    <p class="position">Wioska Smerfów</p>
                    <div class="row">
                        <div class="col-sm-6">
                            <img class="img-responsive employer" src="img/czlowiek.png" alt=""/>
                            <h6>mgr Agnieszka Nowińska</h6>
                            <div class="position">Tomatisa, terapeuta metody Warnkego</div>
                        </div>
                        <div class="col-sm-6">
                            <img class="img-responsive employer" src="img/czlowiek.png" alt=""/>
                            <h6>mgr Agnieszka Nowińska</h6>
                            <div class="position">Tomatisa, terapeuta metody Warnkego</div>
                        </div>
                    </div>
                </div>

                <div class="col-sm-6">
                    <p class="position">Wioska Smerfów</p>
                    <div class="row">
                        <div class="col-sm-6">
                            <img class="img-responsive employer" src="img/czlowiek.png" alt=""/>
                            <h6>mgr Agnieszka Nowińska</h6>
                            <div class="position">Tomatisa, terapeuta metody Warnkego</div>
                        </div>
                        <div class="col-sm-6">
                            <img class="img-responsive employer" src="img/czlowiek.png" alt=""/>
                            <h6>mgr Agnieszka Nowińska</h6>
                            <div class="position">Tomatisa, terapeuta metody Warnkego</div>
                        </div>
                    </div>
                </div>

                <div class="clear"></div>

            </div>

        </div>
    </div>

</div>