<div class="row content">

    <div class="col-sm-12 head">
        <div class="container">
            <h1>nasza kadra</h1>
        </div>
    </div>

    <div class="col-sm-12">
        <div class="container text">
            <div class="clear"></div>

            <?php $bosses = array_chunk($bosses, 2) ?>
            <?php foreach($bosses as $boss): ?>

                <div class="row">

                    <?php /* @var $b \CmsIr\Users\Model\Users */ ?>
                    <?php foreach($boss as $b): ?>

                        <div class="col-sm-6">
                            <img class="img-responsive employer" src="/files/users/<?php echo $b->getFilename() ?>" alt=""/>
                            <h6><?php echo $b->getName() ?>  <?php echo $b->getSurname() ?></h6>
                            <div class="position"><?php echo $b-> getPositionDescription() ?></div>
                        </div>

                    <?php endforeach ?>

                </div>

            <?php endforeach ?>

            <div class="clear"></div>
            <div class="row">

                <?php $people = array_chunk($people, 4) ?>
                <?php foreach($people as $boss): ?>

                    <div class="row">

                        <?php /* @var $b \CmsIr\Users\Model\Users */ ?>
                        <?php foreach($boss as $b): ?>

                            <div class="col-sm-3">
                                <img class="img-responsive employer" src="/files/users/<?php echo $b->getFilename() ?>" alt=""/>
                                <h6><?php echo $b->getName() ?>  <?php echo $b->getSurname() ?></h6>
                                <div class="position"><?php echo $b-> getPositionDescription() ?></div>
                            </div>

                        <?php endforeach ?>

                        <div class="clear"></div>

                    </div>

                <?php endforeach ?>

            </div>

        </div>
    </div>


    <div class="col-sm-12 head">
        <div class="container">
            <div class="clear"></div>
            <h1>wychowawcy grup</h1>
        </div>
    </div>

    <div class="col-sm-12">
        <div class="container text">

            <div class="clear"></div>
            <div class="row">


                <?php /* @var $type \CmsIr\Dictionary\Model\Dictionary */ ?>
                    <?php  foreach($typesOfGroups as $type): ?>

                        <div class="col-sm-6">
                            <p class="position"><?php echo $type->getName() ?></p>
                            <div class="row">

                                <?php /* @var $group \CmsIr\Users\Model\Users */ ?>
                                <?php foreach($groups as $group): ?>

                                    <?php if($type->getId() == $group->getDictionaryGroupId()): ?>

                                        <div class="col-sm-6">
                                            <img class="img-responsive employer" src="/files/users/<?php echo $group->getFilename() ?>" alt=""/>
                                            <h6><?php echo $group->getName() ?>  <?php echo $group->getSurname() ?></h6>
                                            <div class="position"><?php echo mb_substr($group->getPositionDescription(), 0, 50, 'utf-8') ?> ...</div>
                                        </div>

                                    <?php endif ?>

                                <?php endforeach ?>

                            </div>
                        </div>


                <?php endforeach ?>

                <div class="clear"></div>

            </div>

        </div>
    </div>

</div>