<div class="row header">
    <div class="container">
        <header>
            <a href="#" class="show-hide-menu"><img src="/img/menu.png" alt=""/></a>
            <div class="col-sm-5">
                <img src="/img/pro-logo.png" onclick="window.location.href='/pro-communications'" style="cursor: pointer" alt=""/>
            </div>
            <div class="col-sm-7">
                <div class="drop grayscale">

                    <?php echo $this->menuHelper()->renderMenu($menu, 'menuH decor1', null, null, null); ?>

                </div>
            </div>
        </header>
    </div>
</div>

<div class="row">
    <!-- BEGIN HEADER FULL IMAGE SLIDE -->
    <div class="full-slide-image" id="full-img-slide">
        <div class="slide-inner">
            <div class="slide-text-content">
                <div class="container-fluid">
                    <div id="content-header-slide" class="owl-carousel">
                        <?php $items = $slider->getItems() ?>
                        <?php /* @var $item \CmsIr\Slider\Model\SliderItem */ ?>
                        <?php foreach($items as $item): ?>

                            <div class="item">
                                <img src="<?php echo $this->url('thumb', array('entity' => 'slider', 'size' => '2000x600', 'filename' => $item->getFilename() )); ?>" class="img-responsive" alt="image"/>
                                <div class="container">
                                    <h1><?php echo $item->getTitle() ?></h1>
                                    <div class="clear"></div>
                                    <h3><?php echo $item->getDescription() ?></h3>
                                </div>
                            </div>

                        <?php endforeach ?>
                    </div><!-- /.#content-header-slide -->
                </div><!-- /.container -->
            </div><!-- /.slide-text-content -->
        </div><!-- /.slide-inner -->
    </div><!-- /.full-slide-image -->
    <!-- END HEADER FULL IMAGE SLIDE -->
</div>