<?php echo $this->partial('partial/flashmessages-price'); ?>
    <!-- BEGIN DATA TABLE -->
    <input type="hidden" id="category" value="<?php echo $category; ?>" />
    <div class="the-box">
        <div class="table-responsive">
            <table class="table table-striped table-hover" id="datatable-price">
                <thead class="the-box dark full">
                <tr>
                    <th>Nazwa</th>
                    <th class="action-column">Akcje</th>
                </tr>
                </thead>
            </table>

            <div class="row">
                <div class="col-sm-12">
                    <a class="btn btn-facebook pull-right" href="<?php echo $this->url('price/create', array('category' => $category)); ?>">Dodaj nową</a>
                </div>
            </div>

        </div><!-- /.table-responsive -->
    </div><!-- /.the-box .default -->
    <!-- END DATA TABLE -->
<?php echo $this->partial('partial/delete-price-modal'); ?>

<?php $this->headLink()->appendStylesheet($this->basePath().'/css/jquery.dataTables.css'); ?>
<?php $this->headLink()->appendStylesheet($this->basePath().'/css/bootstrap.datatable.min.css'); ?>
<?php $this->headLink()->appendStylesheet($this->basePath().'/css/price.css'); ?>

<?php $this->headScript()->appendFile($this->basePath().'/js/jquery.dataTables.min.js'); ?>
<?php $this->headScript()->appendFile($this->basePath().'/js/bootstrap.datatable.js'); ?>
<?php $this->headScript()->appendFile($this->basePath().'/js/price-list.js'); ?>